language: python
dist: bionic
cache: pip

python:
  - "3.6"
  - "3.7"
  -
addons:
  apt:
    update: true
    packages:
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev

before_script:
  - python3 -m tmtoolkit setup test

script:
  - pytest
