language: python
dist: bionic
cache: pip

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get -y install libgmp-dev libmpfr-dev libmpc-dev
addons:
  apt:
    update: true

before_script:
  - python3 -m tmtoolkit setup test

script:
  - pytest
