name: run tests

on:
  push:
    branches:
      - master
      - develop
      - 'release*'

jobs:
  build:
    runs-on: windows-2019    # TODO: add MacOS, Win
    strategy:
      matrix:
        python-version: ["3.8"]  # ["3.8", "3.9", "3.10"]  # TODO re-enable all
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install system dependencies
        # only managed to install system dependencies on Linux runners
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libgmp-dev libmpfr-dev libmpc-dev
          fi
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: run tox
        # since system dependencies could only be installed on Linux runners, we run the "full" suite only on Linux;
        # on all other OS we run the "recommendedextra" suite
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            tox -e py-full
          else
            tox -e py-recommendedextra
          fi
