name: run tests

on:
  push:
    branches:
      - master
      - develop
      - 'release*'

jobs:
  build:
    runs-on: macos-11    # TODO: add MacOS, Win
    strategy:
      matrix:
        python-version: ["3.8"]  # ["3.8", "3.9", "3.10"]  # TODO re-enable all
    steps:
      - uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: install system dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libgmp-dev libmpfr-dev libmpc-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew update
            brew install icu4c
          fi
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: run tox
        run: tox -e py-full
